### PR TITLE
Fixed svg rendering  [#93461996]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by knowuh** [comment]
This looks good, but I don't quite trust myself. I had some trouble understanding all the recursive callback paths. I am somewhat concerned that this will be hard to debug in the future. Do you have any interest in trying to gussy this up a bit, or ideas to possibly smooth it out?  I could also take a stab at it a bit later, and run it by you.

**Comment by dougmartin** [comment]
@knowuh Would a top level file comment showing a call path for an iframed file work?

**Comment by knowuh** [comment]
@dougmartin it sounds like a good idea to have that call path in the documentation. Thanks.

**Comment by dougmartin** [comment]
I added a flattened call tree at the top of the page and comments on each function.

**Pull request merged**
