### PR TITLE
Added server side fixup of single quoted client metadata attributes [#98586586]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by dougmartin** [comment]
@scytacki @knowuh - this works locally on my phantom test environment using the current html being sent to the server.

**Comment by scytacki** [comment]
@dougmartin can you add a before and after string as a comment to this code.  Something like: "This string was breaking phantom: [], the code here changes it to this string [] which works in phantom"

A test that verifies the code does the right conversion would be even better, but only if it is easy to add.

**Comment by dougmartin** [comment]
I changed the numeric regex placeholders to variable names and added tests which also serve as example transformations.  The tests do not run by default.

**Comment by scytacki** [comment]
Thank you, it is more clear now.  @knowuh what do you think?

**Comment by knowuh** [comment]
Yup, looks better.  Thanks.

**Pull request merged**
