### PR TITLE
Remove temporary files created when using S3 storage.

### PR DESCRIPTION
**Pull request by knowuh**
@scytacki  please review if you get a chance.

An attempt to prevent /tmp filesystem from getting filled.

### CODE REVIEW

**Comment by scytacki** [comment]
My understanding is that the call to `write` is synchronous. Is that correct?
And also we aren't handling any exceptions in the S3Storage class or the code that is instantiating it, right? I could imaging Fog throws a exception sometimes, but hopefully it is rare.

**Comment by knowuh** [comment]
Even though the local variable name here is 'stream_file', I am pretty sure `bucket.files.create` is synchronous. I have been looking for 10 minutes, and haven't found confirmation anywhere for this yet. And you are right, we should start at least log AWS exceptions on write attempts.

**Comment by scytacki** [comment]
I was thinking about the exceptions, because if one was thrown then the temporary file wouldn't be cleaned up. So to be safe you might want to put the file deletion code in a `ensure` block.

**Comment by knowuh** [comment]
At first I wasn't sure this was a good idea.  I thought it might be better to have the temporary file on the file system for poking around.  But realized we never really do that sort of forensic work, and its unlikely that whatever the temp files contained would be the cause of the S3 upload problem.

I didn't try any rescue. I figure its better to let the exception reporting mechanisms handle it.

**Comment by scytacki** [comment]
:+1:

**Pull request merged**
